version: '3'
services:
  my-app:
    build: .
    ports:
    - "8889:80"

  db:
    image: "postgres:11"
    container_name: "postgres_database"
    environment:
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_USER=postgres
      - POSTGRES_DB=finances
    ports:
      - "332768:32768"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}